### ISSUE TITLE
Cannot import name ABC

### ISSUE THREAD

**Issue by RoyDJ84** [jacopo-j/HypeAPI#1]
non riesco a farlo funzionare, dice che banking ha un problema ad importare abc

**Comment by jacopo-j** [comment]
Questo modulo richiede Python 3.4 o successivo. Che versione stai usando?

**Comment by RoyDJ84** [comment]
2.7.18 su win 7 x64
provato la 3.7.3 e si ferma su linea 5 di banking, import requiredlogin.
la 3.8.3 non me la fa proprio installare

Traceback (most recent call last):
  File "D:\Download\HypeAPI-master\provo.py", line 1, in <module>
    import banking
  File "D:\Download\HypeAPI-master\banking.py", line 5, in <module>
    from utils import loginrequired
  File "D:\Download\HypeAPI-master\utils.py", line 4, in <module>
    from lxml import html
ModuleNotFoundError: No module named 'lxml'



provo.py contine il codice di esempio con relativi dati di accesso
