### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by sciorty** [jacopo-j/HypeAPI#3]
Grazie per la fantastica repo che uso felicemente da ormai 3 anni per fare un report mensile delle mie spese nette.

Oggi di punto in bianco ricevo questo errore quando chiedo la lista dei movimenti (user, password e otp sono corretti)

```
Traceback (most recent call last):
  File "[..]\Hype_GoogleDrive_Sync.py", line 32, in <module>
    json_data=h.get_movements(3000) #last 3000 movemente
              ^^^^^^^^^^^^^^^^^^^^^
  File "[..]\utils.py", line 27, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..]\hype.py", line 168, in get_movements
    return self._api_request(method="GET", url=self.MOVEMENTS_URL.format(limit))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..]\banking.py", line 79, in _api_request
    raise self.AuthenticationFailure
banking.Banking.AuthenticationFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[..]\Hype_GoogleDrive_Sync.py", line 44, in <module>
    h.get_card_info()
  File "[..]\utils.py", line 27, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..]\banking.py", line 109, in get_card_info
    return self._api_request(method="GET", url=self.CARD_URL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..]\banking.py", line 79, in _api_request
    raise self.AuthenticationFailure
banking.Banking.AuthenticationFailure

```

**Comment by pyccino** [comment]
Anche io ho ricevuto lo stesso errore (password e otp sono corretti), Te per caso sei riuscito a farlo funzionare?

**Comment by pyccino** [comment]
Mi sono messo con Charles proxy a vedere le richieste dell'app per mettere a posto la libreria, ed è cambiato tutto: modo di autenticarsi, i vari ep etc.

E dando uno sguardo veloce mi sa che pensare di rifare una libreria così non è possibile almeno che non ci si metta a decompilare l'app

**Comment by sciorty** [comment]
Uffa.. avevo basato il monitoraggio delle mie spese su questa libreria, per creare un excel con dei grafici! Mi sa che adesso l’unica opzione è importare manualmente l’excel che crea l’app
